name: check_in

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    name: do_checkin
    runs-on: ubuntu-latest
    env: 
      USERNAME: ${{secrets.USERNAME}}
      PASSWORD: ${{secrets.PASSWORD}}
      JZDXXDZ: ${{secrets.JZDXXDZ}}
      LONGITUDE: ${{secrets.LONGITUDE}}
      LATITUDE: ${{secrets.LATITUDE}}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Export Env
        run: |
          ${{secrets.NOTIFICATIONTYPES}} $$ echo ${{secrets.NOTIFICATIONTYPES}} >> $GITHUB_ENV
          ${{secrets.PUSHPLUSTOKEN}} && echo ${{secrets.PUSHPLUSTOKEN}} >> $GITHUB_ENV
          ${{secrets.PUSHPLUSTOPIC}} && echo ${{secrets.PUSHPLUSTOPIC}} >> $GITHUB_ENV
          ${{secrets.TELEGRAMBOTTOKEN}} && echo ${{secrets.TELEGRAMBOTTOKEN}} >> $GITHUB_ENV
          ${{secrets.TELEGRAMBOTCHATID}} && echo ${{secrets.TELEGRAMBOTCHATID}} >> $GITHUB_ENV
          ${{secrets.WXPUSHERTOKEN}} && echo ${{secrets.WXPUSHERTOKEN}} >> $GITHUB_ENV
          ${{secrets.WXPUSHERUIDS}} && echo ${{secrets.WXPUSHERUIDS}} >> $GITHUB_ENV
          ${{secrets.WXPUSHERTOPICIDS}} && echo ${{secrets.WXPUSHERTOPICIDS}} >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run
        run: python3 cqupt_checkin.py 
